num_classes: 10
epochs: 60
grad_clip: 5.0
log_frequency: 100

model:
  name: ResNet18
  num_classes: 10


criterion:
#  name: MeanAbsoluteError
  name: CrossEntropyLoss

optimizer:
  name: SGD
  lr: 0.03
  weight_decay: 5.e-4
  momentum: 0.9

scheduler:
  name: CosineAnnealingLR
  T_max: $epochs
  eta_min: 0.0

dataset:
  name: DatasetGenerator
  train_batch_size: 128
  eval_batch_size: 128


clustering_model:
  setup: scan
  # Model
  backbone: resnet18
  train_db_name: cifar-10
  num_classes: 10
  num_heads: 1
  clustering_model_path: C:\Users\zhangyisheng\Desktop\My-Unsupervised-Classification-master\results\cifar-10\scan\model.pth.tar